// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	grpc "google.golang.org/grpc"

	mock "github.com/stretchr/testify/mock"

	proto "github.com/cirglo.com/dfs/pkg/proto"
)

// NameInternalClient is an autogenerated mock type for the NameInternalClient type
type NameInternalClient struct {
	mock.Mock
}

type NameInternalClient_Expecter struct {
	mock *mock.Mock
}

func (_m *NameInternalClient) EXPECT() *NameInternalClient_Expecter {
	return &NameInternalClient_Expecter{mock: &_m.Mock}
}

// NotifyBlocksAdded provides a mock function with given fields: ctx, in, opts
func (_m *NameInternalClient) NotifyBlocksAdded(ctx context.Context, in *proto.BlockInfoReport, opts ...grpc.CallOption) (*proto.BlockInfoReportResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for NotifyBlocksAdded")
	}

	var r0 *proto.BlockInfoReportResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *proto.BlockInfoReport, ...grpc.CallOption) (*proto.BlockInfoReportResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *proto.BlockInfoReport, ...grpc.CallOption) *proto.BlockInfoReportResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*proto.BlockInfoReportResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *proto.BlockInfoReport, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NameInternalClient_NotifyBlocksAdded_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NotifyBlocksAdded'
type NameInternalClient_NotifyBlocksAdded_Call struct {
	*mock.Call
}

// NotifyBlocksAdded is a helper method to define mock.On call
//   - ctx context.Context
//   - in *proto.BlockInfoReport
//   - opts ...grpc.CallOption
func (_e *NameInternalClient_Expecter) NotifyBlocksAdded(ctx interface{}, in interface{}, opts ...interface{}) *NameInternalClient_NotifyBlocksAdded_Call {
	return &NameInternalClient_NotifyBlocksAdded_Call{Call: _e.mock.On("NotifyBlocksAdded",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *NameInternalClient_NotifyBlocksAdded_Call) Run(run func(ctx context.Context, in *proto.BlockInfoReport, opts ...grpc.CallOption)) *NameInternalClient_NotifyBlocksAdded_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		run(args[0].(context.Context), args[1].(*proto.BlockInfoReport), variadicArgs...)
	})
	return _c
}

func (_c *NameInternalClient_NotifyBlocksAdded_Call) Return(_a0 *proto.BlockInfoReportResponse, _a1 error) *NameInternalClient_NotifyBlocksAdded_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *NameInternalClient_NotifyBlocksAdded_Call) RunAndReturn(run func(context.Context, *proto.BlockInfoReport, ...grpc.CallOption) (*proto.BlockInfoReportResponse, error)) *NameInternalClient_NotifyBlocksAdded_Call {
	_c.Call.Return(run)
	return _c
}

// NotifyBlocksRemoved provides a mock function with given fields: ctx, in, opts
func (_m *NameInternalClient) NotifyBlocksRemoved(ctx context.Context, in *proto.BlockInfoReport, opts ...grpc.CallOption) (*proto.BlockInfoReportResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for NotifyBlocksRemoved")
	}

	var r0 *proto.BlockInfoReportResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *proto.BlockInfoReport, ...grpc.CallOption) (*proto.BlockInfoReportResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *proto.BlockInfoReport, ...grpc.CallOption) *proto.BlockInfoReportResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*proto.BlockInfoReportResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *proto.BlockInfoReport, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NameInternalClient_NotifyBlocksRemoved_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NotifyBlocksRemoved'
type NameInternalClient_NotifyBlocksRemoved_Call struct {
	*mock.Call
}

// NotifyBlocksRemoved is a helper method to define mock.On call
//   - ctx context.Context
//   - in *proto.BlockInfoReport
//   - opts ...grpc.CallOption
func (_e *NameInternalClient_Expecter) NotifyBlocksRemoved(ctx interface{}, in interface{}, opts ...interface{}) *NameInternalClient_NotifyBlocksRemoved_Call {
	return &NameInternalClient_NotifyBlocksRemoved_Call{Call: _e.mock.On("NotifyBlocksRemoved",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *NameInternalClient_NotifyBlocksRemoved_Call) Run(run func(ctx context.Context, in *proto.BlockInfoReport, opts ...grpc.CallOption)) *NameInternalClient_NotifyBlocksRemoved_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		run(args[0].(context.Context), args[1].(*proto.BlockInfoReport), variadicArgs...)
	})
	return _c
}

func (_c *NameInternalClient_NotifyBlocksRemoved_Call) Return(_a0 *proto.BlockInfoReportResponse, _a1 error) *NameInternalClient_NotifyBlocksRemoved_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *NameInternalClient_NotifyBlocksRemoved_Call) RunAndReturn(run func(context.Context, *proto.BlockInfoReport, ...grpc.CallOption) (*proto.BlockInfoReportResponse, error)) *NameInternalClient_NotifyBlocksRemoved_Call {
	_c.Call.Return(run)
	return _c
}

// ReportExistingBlocks provides a mock function with given fields: ctx, in, opts
func (_m *NameInternalClient) ReportExistingBlocks(ctx context.Context, in *proto.BlockInfoReport, opts ...grpc.CallOption) (*proto.BlockInfoReportResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for ReportExistingBlocks")
	}

	var r0 *proto.BlockInfoReportResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *proto.BlockInfoReport, ...grpc.CallOption) (*proto.BlockInfoReportResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *proto.BlockInfoReport, ...grpc.CallOption) *proto.BlockInfoReportResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*proto.BlockInfoReportResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *proto.BlockInfoReport, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NameInternalClient_ReportExistingBlocks_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReportExistingBlocks'
type NameInternalClient_ReportExistingBlocks_Call struct {
	*mock.Call
}

// ReportExistingBlocks is a helper method to define mock.On call
//   - ctx context.Context
//   - in *proto.BlockInfoReport
//   - opts ...grpc.CallOption
func (_e *NameInternalClient_Expecter) ReportExistingBlocks(ctx interface{}, in interface{}, opts ...interface{}) *NameInternalClient_ReportExistingBlocks_Call {
	return &NameInternalClient_ReportExistingBlocks_Call{Call: _e.mock.On("ReportExistingBlocks",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *NameInternalClient_ReportExistingBlocks_Call) Run(run func(ctx context.Context, in *proto.BlockInfoReport, opts ...grpc.CallOption)) *NameInternalClient_ReportExistingBlocks_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		run(args[0].(context.Context), args[1].(*proto.BlockInfoReport), variadicArgs...)
	})
	return _c
}

func (_c *NameInternalClient_ReportExistingBlocks_Call) Return(_a0 *proto.BlockInfoReportResponse, _a1 error) *NameInternalClient_ReportExistingBlocks_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *NameInternalClient_ReportExistingBlocks_Call) RunAndReturn(run func(context.Context, *proto.BlockInfoReport, ...grpc.CallOption) (*proto.BlockInfoReportResponse, error)) *NameInternalClient_ReportExistingBlocks_Call {
	_c.Call.Return(run)
	return _c
}

// NewNameInternalClient creates a new instance of NameInternalClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewNameInternalClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *NameInternalClient {
	mock := &NameInternalClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
