// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: internal.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BlockInfoReport struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Host          string                 `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`
	BlockInfos    []*BlockInfoItem       `protobuf:"bytes,3,rep,name=blockInfos,proto3" json:"blockInfos,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlockInfoReport) Reset() {
	*x = BlockInfoReport{}
	mi := &file_internal_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlockInfoReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockInfoReport) ProtoMessage() {}

func (x *BlockInfoReport) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockInfoReport.ProtoReflect.Descriptor instead.
func (*BlockInfoReport) Descriptor() ([]byte, []int) {
	return file_internal_proto_rawDescGZIP(), []int{0}
}

func (x *BlockInfoReport) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *BlockInfoReport) GetBlockInfos() []*BlockInfoItem {
	if x != nil {
		return x.BlockInfos
	}
	return nil
}

type BlockInfoItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BlockId       string                 `protobuf:"bytes,1,opt,name=blockId,proto3" json:"blockId,omitempty"`
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	Crc           uint32                 `protobuf:"varint,3,opt,name=crc,proto3" json:"crc,omitempty"`
	Sequence      uint64                 `protobuf:"varint,4,opt,name=sequence,proto3" json:"sequence,omitempty"`
	Length        uint32                 `protobuf:"varint,5,opt,name=length,proto3" json:"length,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlockInfoItem) Reset() {
	*x = BlockInfoItem{}
	mi := &file_internal_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlockInfoItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockInfoItem) ProtoMessage() {}

func (x *BlockInfoItem) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockInfoItem.ProtoReflect.Descriptor instead.
func (*BlockInfoItem) Descriptor() ([]byte, []int) {
	return file_internal_proto_rawDescGZIP(), []int{1}
}

func (x *BlockInfoItem) GetBlockId() string {
	if x != nil {
		return x.BlockId
	}
	return ""
}

func (x *BlockInfoItem) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *BlockInfoItem) GetCrc() uint32 {
	if x != nil {
		return x.Crc
	}
	return 0
}

func (x *BlockInfoItem) GetSequence() uint64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *BlockInfoItem) GetLength() uint32 {
	if x != nil {
		return x.Length
	}
	return 0
}

type BlockInfoReportResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlockInfoReportResponse) Reset() {
	*x = BlockInfoReportResponse{}
	mi := &file_internal_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlockInfoReportResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockInfoReportResponse) ProtoMessage() {}

func (x *BlockInfoReportResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockInfoReportResponse.ProtoReflect.Descriptor instead.
func (*BlockInfoReportResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_rawDescGZIP(), []int{2}
}

var File_internal_proto protoreflect.FileDescriptor

const file_internal_proto_rawDesc = "" +
	"\n" +
	"\x0einternal.proto\x12\n" +
	"nameserver\"`\n" +
	"\x0fBlockInfoReport\x12\x12\n" +
	"\x04host\x18\x01 \x01(\tR\x04host\x129\n" +
	"\n" +
	"blockInfos\x18\x03 \x03(\v2\x19.nameserver.BlockInfoItemR\n" +
	"blockInfos\"\x83\x01\n" +
	"\rBlockInfoItem\x12\x18\n" +
	"\ablockId\x18\x01 \x01(\tR\ablockId\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x12\x10\n" +
	"\x03crc\x18\x03 \x01(\rR\x03crc\x12\x1a\n" +
	"\bsequence\x18\x04 \x01(\x04R\bsequence\x12\x16\n" +
	"\x06length\x18\x05 \x01(\rR\x06length\"\x19\n" +
	"\x17BlockInfoReportResponse2\x98\x02\n" +
	"\fNameInternal\x12X\n" +
	"\x14ReportExistingBlocks\x12\x1b.nameserver.BlockInfoReport\x1a#.nameserver.BlockInfoReportResponse\x12U\n" +
	"\x11NotifyBlocksAdded\x12\x1b.nameserver.BlockInfoReport\x1a#.nameserver.BlockInfoReportResponse\x12W\n" +
	"\x13NotifyBlocksRemoved\x12\x1b.nameserver.BlockInfoReport\x1a#.nameserver.BlockInfoReportResponseB\n" +
	"Z\b./;protob\x06proto3"

var (
	file_internal_proto_rawDescOnce sync.Once
	file_internal_proto_rawDescData []byte
)

func file_internal_proto_rawDescGZIP() []byte {
	file_internal_proto_rawDescOnce.Do(func() {
		file_internal_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_proto_rawDesc), len(file_internal_proto_rawDesc)))
	})
	return file_internal_proto_rawDescData
}

var file_internal_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_internal_proto_goTypes = []any{
	(*BlockInfoReport)(nil),         // 0: nameserver.BlockInfoReport
	(*BlockInfoItem)(nil),           // 1: nameserver.BlockInfoItem
	(*BlockInfoReportResponse)(nil), // 2: nameserver.BlockInfoReportResponse
}
var file_internal_proto_depIdxs = []int32{
	1, // 0: nameserver.BlockInfoReport.blockInfos:type_name -> nameserver.BlockInfoItem
	0, // 1: nameserver.NameInternal.ReportExistingBlocks:input_type -> nameserver.BlockInfoReport
	0, // 2: nameserver.NameInternal.NotifyBlocksAdded:input_type -> nameserver.BlockInfoReport
	0, // 3: nameserver.NameInternal.NotifyBlocksRemoved:input_type -> nameserver.BlockInfoReport
	2, // 4: nameserver.NameInternal.ReportExistingBlocks:output_type -> nameserver.BlockInfoReportResponse
	2, // 5: nameserver.NameInternal.NotifyBlocksAdded:output_type -> nameserver.BlockInfoReportResponse
	2, // 6: nameserver.NameInternal.NotifyBlocksRemoved:output_type -> nameserver.BlockInfoReportResponse
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_internal_proto_init() }
func file_internal_proto_init() {
	if File_internal_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_proto_rawDesc), len(file_internal_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_proto_goTypes,
		DependencyIndexes: file_internal_proto_depIdxs,
		MessageInfos:      file_internal_proto_msgTypes,
	}.Build()
	File_internal_proto = out.File
	file_internal_proto_goTypes = nil
	file_internal_proto_depIdxs = nil
}
