// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: nameserver.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Permission struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Read          bool                   `protobuf:"varint,1,opt,name=read,proto3" json:"read,omitempty"`
	Write         bool                   `protobuf:"varint,2,opt,name=write,proto3" json:"write,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Permission) Reset() {
	*x = Permission{}
	mi := &file_nameserver_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Permission) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Permission) ProtoMessage() {}

func (x *Permission) ProtoReflect() protoreflect.Message {
	mi := &file_nameserver_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Permission.ProtoReflect.Descriptor instead.
func (*Permission) Descriptor() ([]byte, []int) {
	return file_nameserver_proto_rawDescGZIP(), []int{0}
}

func (x *Permission) GetRead() bool {
	if x != nil {
		return x.Read
	}
	return false
}

func (x *Permission) GetWrite() bool {
	if x != nil {
		return x.Write
	}
	return false
}

type Permissions struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Owner           string                 `protobuf:"bytes,1,opt,name=owner,proto3" json:"owner,omitempty"`
	Group           string                 `protobuf:"bytes,2,opt,name=group,proto3" json:"group,omitempty"`
	OwnerPermission *Permission            `protobuf:"bytes,3,opt,name=ownerPermission,proto3" json:"ownerPermission,omitempty"`
	GroupPermission *Permission            `protobuf:"bytes,4,opt,name=groupPermission,proto3" json:"groupPermission,omitempty"`
	OtherPermission *Permission            `protobuf:"bytes,5,opt,name=otherPermission,proto3" json:"otherPermission,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Permissions) Reset() {
	*x = Permissions{}
	mi := &file_nameserver_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Permissions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Permissions) ProtoMessage() {}

func (x *Permissions) ProtoReflect() protoreflect.Message {
	mi := &file_nameserver_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Permissions.ProtoReflect.Descriptor instead.
func (*Permissions) Descriptor() ([]byte, []int) {
	return file_nameserver_proto_rawDescGZIP(), []int{1}
}

func (x *Permissions) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *Permissions) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

func (x *Permissions) GetOwnerPermission() *Permission {
	if x != nil {
		return x.OwnerPermission
	}
	return nil
}

func (x *Permissions) GetGroupPermission() *Permission {
	if x != nil {
		return x.GroupPermission
	}
	return nil
}

func (x *Permissions) GetOtherPermission() *Permission {
	if x != nil {
		return x.OtherPermission
	}
	return nil
}

type DirEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	IsDir         bool                   `protobuf:"varint,2,opt,name=isDir,proto3" json:"isDir,omitempty"`
	Permissions   *Permissions           `protobuf:"bytes,3,opt,name=permissions,proto3" json:"permissions,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,4,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	ModifiedAt    int64                  `protobuf:"varint,5,opt,name=modifiedAt,proto3" json:"modifiedAt,omitempty"`
	AccessedAt    int64                  `protobuf:"varint,6,opt,name=accessedAt,proto3" json:"accessedAt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DirEntry) Reset() {
	*x = DirEntry{}
	mi := &file_nameserver_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DirEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DirEntry) ProtoMessage() {}

func (x *DirEntry) ProtoReflect() protoreflect.Message {
	mi := &file_nameserver_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DirEntry.ProtoReflect.Descriptor instead.
func (*DirEntry) Descriptor() ([]byte, []int) {
	return file_nameserver_proto_rawDescGZIP(), []int{2}
}

func (x *DirEntry) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *DirEntry) GetIsDir() bool {
	if x != nil {
		return x.IsDir
	}
	return false
}

func (x *DirEntry) GetPermissions() *Permissions {
	if x != nil {
		return x.Permissions
	}
	return nil
}

func (x *DirEntry) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *DirEntry) GetModifiedAt() int64 {
	if x != nil {
		return x.ModifiedAt
	}
	return 0
}

func (x *DirEntry) GetAccessedAt() int64 {
	if x != nil {
		return x.AccessedAt
	}
	return 0
}

type StatBlockInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Host          string                 `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`
	Port          uint32                 `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	BlockId       string                 `protobuf:"bytes,3,opt,name=blockId,proto3" json:"blockId,omitempty"`
	Crc           uint32                 `protobuf:"varint,5,opt,name=crc,proto3" json:"crc,omitempty"`
	Sequence      uint64                 `protobuf:"varint,6,opt,name=sequence,proto3" json:"sequence,omitempty"`
	Length        uint32                 `protobuf:"varint,7,opt,name=length,proto3" json:"length,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatBlockInfo) Reset() {
	*x = StatBlockInfo{}
	mi := &file_nameserver_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatBlockInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatBlockInfo) ProtoMessage() {}

func (x *StatBlockInfo) ProtoReflect() protoreflect.Message {
	mi := &file_nameserver_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatBlockInfo.ProtoReflect.Descriptor instead.
func (*StatBlockInfo) Descriptor() ([]byte, []int) {
	return file_nameserver_proto_rawDescGZIP(), []int{3}
}

func (x *StatBlockInfo) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *StatBlockInfo) GetPort() uint32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *StatBlockInfo) GetBlockId() string {
	if x != nil {
		return x.BlockId
	}
	return ""
}

func (x *StatBlockInfo) GetCrc() uint32 {
	if x != nil {
		return x.Crc
	}
	return 0
}

func (x *StatBlockInfo) GetSequence() uint64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *StatBlockInfo) GetLength() uint32 {
	if x != nil {
		return x.Length
	}
	return 0
}

type LoginRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	User           string                 `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	HashedPassword string                 `protobuf:"bytes,2,opt,name=hashedPassword,proto3" json:"hashedPassword,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	mi := &file_nameserver_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nameserver_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequest.ProtoReflect.Descriptor instead.
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return file_nameserver_proto_rawDescGZIP(), []int{4}
}

func (x *LoginRequest) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *LoginRequest) GetHashedPassword() string {
	if x != nil {
		return x.HashedPassword
	}
	return ""
}

type LoginResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          string                 `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	Token         string                 `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginResponse) Reset() {
	*x = LoginResponse{}
	mi := &file_nameserver_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResponse) ProtoMessage() {}

func (x *LoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nameserver_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResponse.ProtoReflect.Descriptor instead.
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return file_nameserver_proto_rawDescGZIP(), []int{5}
}

func (x *LoginResponse) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *LoginResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type LogoutRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogoutRequest) Reset() {
	*x = LogoutRequest{}
	mi := &file_nameserver_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogoutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogoutRequest) ProtoMessage() {}

func (x *LogoutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nameserver_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogoutRequest.ProtoReflect.Descriptor instead.
func (*LogoutRequest) Descriptor() ([]byte, []int) {
	return file_nameserver_proto_rawDescGZIP(), []int{6}
}

func (x *LogoutRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type LogoutResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogoutResponse) Reset() {
	*x = LogoutResponse{}
	mi := &file_nameserver_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogoutResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogoutResponse) ProtoMessage() {}

func (x *LogoutResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nameserver_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogoutResponse.ProtoReflect.Descriptor instead.
func (*LogoutResponse) Descriptor() ([]byte, []int) {
	return file_nameserver_proto_rawDescGZIP(), []int{7}
}

type CreateFileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	Permissions   *Permissions           `protobuf:"bytes,3,opt,name=permissions,proto3" json:"permissions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateFileRequest) Reset() {
	*x = CreateFileRequest{}
	mi := &file_nameserver_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateFileRequest) ProtoMessage() {}

func (x *CreateFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nameserver_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateFileRequest.ProtoReflect.Descriptor instead.
func (*CreateFileRequest) Descriptor() ([]byte, []int) {
	return file_nameserver_proto_rawDescGZIP(), []int{8}
}

func (x *CreateFileRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *CreateFileRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *CreateFileRequest) GetPermissions() *Permissions {
	if x != nil {
		return x.Permissions
	}
	return nil
}

type CreateFileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateFileResponse) Reset() {
	*x = CreateFileResponse{}
	mi := &file_nameserver_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateFileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateFileResponse) ProtoMessage() {}

func (x *CreateFileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nameserver_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateFileResponse.ProtoReflect.Descriptor instead.
func (*CreateFileResponse) Descriptor() ([]byte, []int) {
	return file_nameserver_proto_rawDescGZIP(), []int{9}
}

type CreateDirRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	Permissions   *Permissions           `protobuf:"bytes,3,opt,name=permissions,proto3" json:"permissions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateDirRequest) Reset() {
	*x = CreateDirRequest{}
	mi := &file_nameserver_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateDirRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDirRequest) ProtoMessage() {}

func (x *CreateDirRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nameserver_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDirRequest.ProtoReflect.Descriptor instead.
func (*CreateDirRequest) Descriptor() ([]byte, []int) {
	return file_nameserver_proto_rawDescGZIP(), []int{10}
}

func (x *CreateDirRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *CreateDirRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *CreateDirRequest) GetPermissions() *Permissions {
	if x != nil {
		return x.Permissions
	}
	return nil
}

type CreateDirResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateDirResponse) Reset() {
	*x = CreateDirResponse{}
	mi := &file_nameserver_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateDirResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDirResponse) ProtoMessage() {}

func (x *CreateDirResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nameserver_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDirResponse.ProtoReflect.Descriptor instead.
func (*CreateDirResponse) Descriptor() ([]byte, []int) {
	return file_nameserver_proto_rawDescGZIP(), []int{11}
}

type DeleteFileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteFileRequest) Reset() {
	*x = DeleteFileRequest{}
	mi := &file_nameserver_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteFileRequest) ProtoMessage() {}

func (x *DeleteFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nameserver_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteFileRequest.ProtoReflect.Descriptor instead.
func (*DeleteFileRequest) Descriptor() ([]byte, []int) {
	return file_nameserver_proto_rawDescGZIP(), []int{12}
}

func (x *DeleteFileRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *DeleteFileRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type DeleteFileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteFileResponse) Reset() {
	*x = DeleteFileResponse{}
	mi := &file_nameserver_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteFileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteFileResponse) ProtoMessage() {}

func (x *DeleteFileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nameserver_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteFileResponse.ProtoReflect.Descriptor instead.
func (*DeleteFileResponse) Descriptor() ([]byte, []int) {
	return file_nameserver_proto_rawDescGZIP(), []int{13}
}

type DeleteDirRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteDirRequest) Reset() {
	*x = DeleteDirRequest{}
	mi := &file_nameserver_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteDirRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteDirRequest) ProtoMessage() {}

func (x *DeleteDirRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nameserver_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteDirRequest.ProtoReflect.Descriptor instead.
func (*DeleteDirRequest) Descriptor() ([]byte, []int) {
	return file_nameserver_proto_rawDescGZIP(), []int{14}
}

func (x *DeleteDirRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *DeleteDirRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type DeleteDirResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteDirResponse) Reset() {
	*x = DeleteDirResponse{}
	mi := &file_nameserver_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteDirResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteDirResponse) ProtoMessage() {}

func (x *DeleteDirResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nameserver_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteDirResponse.ProtoReflect.Descriptor instead.
func (*DeleteDirResponse) Descriptor() ([]byte, []int) {
	return file_nameserver_proto_rawDescGZIP(), []int{15}
}

type ListDirRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDirRequest) Reset() {
	*x = ListDirRequest{}
	mi := &file_nameserver_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDirRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDirRequest) ProtoMessage() {}

func (x *ListDirRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nameserver_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDirRequest.ProtoReflect.Descriptor instead.
func (*ListDirRequest) Descriptor() ([]byte, []int) {
	return file_nameserver_proto_rawDescGZIP(), []int{16}
}

func (x *ListDirRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *ListDirRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type ListDirResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Entries       []*DirEntry            `protobuf:"bytes,2,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDirResponse) Reset() {
	*x = ListDirResponse{}
	mi := &file_nameserver_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDirResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDirResponse) ProtoMessage() {}

func (x *ListDirResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nameserver_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDirResponse.ProtoReflect.Descriptor instead.
func (*ListDirResponse) Descriptor() ([]byte, []int) {
	return file_nameserver_proto_rawDescGZIP(), []int{17}
}

func (x *ListDirResponse) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *ListDirResponse) GetEntries() []*DirEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

type StatFileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatFileRequest) Reset() {
	*x = StatFileRequest{}
	mi := &file_nameserver_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatFileRequest) ProtoMessage() {}

func (x *StatFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nameserver_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatFileRequest.ProtoReflect.Descriptor instead.
func (*StatFileRequest) Descriptor() ([]byte, []int) {
	return file_nameserver_proto_rawDescGZIP(), []int{18}
}

func (x *StatFileRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *StatFileRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type StatFileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Entry         *DirEntry              `protobuf:"bytes,2,opt,name=entry,proto3" json:"entry,omitempty"`
	BlockInfos    []*StatBlockInfo       `protobuf:"bytes,3,rep,name=blockInfos,proto3" json:"blockInfos,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatFileResponse) Reset() {
	*x = StatFileResponse{}
	mi := &file_nameserver_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatFileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatFileResponse) ProtoMessage() {}

func (x *StatFileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nameserver_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatFileResponse.ProtoReflect.Descriptor instead.
func (*StatFileResponse) Descriptor() ([]byte, []int) {
	return file_nameserver_proto_rawDescGZIP(), []int{19}
}

func (x *StatFileResponse) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *StatFileResponse) GetEntry() *DirEntry {
	if x != nil {
		return x.Entry
	}
	return nil
}

func (x *StatFileResponse) GetBlockInfos() []*StatBlockInfo {
	if x != nil {
		return x.BlockInfos
	}
	return nil
}

var File_nameserver_proto protoreflect.FileDescriptor

const file_nameserver_proto_rawDesc = "" +
	"\n" +
	"\x10nameserver.proto\x12\n" +
	"nameserver\"6\n" +
	"\n" +
	"Permission\x12\x12\n" +
	"\x04read\x18\x01 \x01(\bR\x04read\x12\x14\n" +
	"\x05write\x18\x02 \x01(\bR\x05write\"\xff\x01\n" +
	"\vPermissions\x12\x14\n" +
	"\x05owner\x18\x01 \x01(\tR\x05owner\x12\x14\n" +
	"\x05group\x18\x02 \x01(\tR\x05group\x12@\n" +
	"\x0fownerPermission\x18\x03 \x01(\v2\x16.nameserver.PermissionR\x0fownerPermission\x12@\n" +
	"\x0fgroupPermission\x18\x04 \x01(\v2\x16.nameserver.PermissionR\x0fgroupPermission\x12@\n" +
	"\x0fotherPermission\x18\x05 \x01(\v2\x16.nameserver.PermissionR\x0fotherPermission\"\xcd\x01\n" +
	"\bDirEntry\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x14\n" +
	"\x05isDir\x18\x02 \x01(\bR\x05isDir\x129\n" +
	"\vpermissions\x18\x03 \x01(\v2\x17.nameserver.PermissionsR\vpermissions\x12\x1c\n" +
	"\tcreatedAt\x18\x04 \x01(\x03R\tcreatedAt\x12\x1e\n" +
	"\n" +
	"modifiedAt\x18\x05 \x01(\x03R\n" +
	"modifiedAt\x12\x1e\n" +
	"\n" +
	"accessedAt\x18\x06 \x01(\x03R\n" +
	"accessedAt\"\x97\x01\n" +
	"\rStatBlockInfo\x12\x12\n" +
	"\x04host\x18\x01 \x01(\tR\x04host\x12\x12\n" +
	"\x04port\x18\x02 \x01(\rR\x04port\x12\x18\n" +
	"\ablockId\x18\x03 \x01(\tR\ablockId\x12\x10\n" +
	"\x03crc\x18\x05 \x01(\rR\x03crc\x12\x1a\n" +
	"\bsequence\x18\x06 \x01(\x04R\bsequence\x12\x16\n" +
	"\x06length\x18\a \x01(\rR\x06length\"J\n" +
	"\fLoginRequest\x12\x12\n" +
	"\x04user\x18\x01 \x01(\tR\x04user\x12&\n" +
	"\x0ehashedPassword\x18\x02 \x01(\tR\x0ehashedPassword\"9\n" +
	"\rLoginResponse\x12\x12\n" +
	"\x04user\x18\x01 \x01(\tR\x04user\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05token\"%\n" +
	"\rLogoutRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\"\x10\n" +
	"\x0eLogoutResponse\"x\n" +
	"\x11CreateFileRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x129\n" +
	"\vpermissions\x18\x03 \x01(\v2\x17.nameserver.PermissionsR\vpermissions\"\x14\n" +
	"\x12CreateFileResponse\"w\n" +
	"\x10CreateDirRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x129\n" +
	"\vpermissions\x18\x03 \x01(\v2\x17.nameserver.PermissionsR\vpermissions\"\x13\n" +
	"\x11CreateDirResponse\"=\n" +
	"\x11DeleteFileRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\"\x14\n" +
	"\x12DeleteFileResponse\"<\n" +
	"\x10DeleteDirRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\"\x13\n" +
	"\x11DeleteDirResponse\":\n" +
	"\x0eListDirRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\"U\n" +
	"\x0fListDirResponse\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12.\n" +
	"\aentries\x18\x02 \x03(\v2\x14.nameserver.DirEntryR\aentries\";\n" +
	"\x0fStatFileRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\"\x8d\x01\n" +
	"\x10StatFileResponse\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12*\n" +
	"\x05entry\x18\x02 \x01(\v2\x14.nameserver.DirEntryR\x05entry\x129\n" +
	"\n" +
	"blockInfos\x18\x03 \x03(\v2\x19.nameserver.StatBlockInfoR\n" +
	"blockInfos2\xbe\x04\n" +
	"\x04Name\x12<\n" +
	"\x05Login\x12\x18.nameserver.LoginRequest\x1a\x19.nameserver.LoginResponse\x12?\n" +
	"\x06Logout\x12\x19.nameserver.LogoutRequest\x1a\x1a.nameserver.LogoutResponse\x12K\n" +
	"\n" +
	"CreateFile\x12\x1d.nameserver.CreateFileRequest\x1a\x1e.nameserver.CreateFileResponse\x12H\n" +
	"\tCreateDir\x12\x1c.nameserver.CreateDirRequest\x1a\x1d.nameserver.CreateDirResponse\x12K\n" +
	"\n" +
	"DeleteFile\x12\x1d.nameserver.DeleteFileRequest\x1a\x1e.nameserver.DeleteFileResponse\x12H\n" +
	"\tDeleteDir\x12\x1c.nameserver.DeleteDirRequest\x1a\x1d.nameserver.DeleteDirResponse\x12B\n" +
	"\aListDir\x12\x1a.nameserver.ListDirRequest\x1a\x1b.nameserver.ListDirResponse\x12E\n" +
	"\bStatFile\x12\x1b.nameserver.StatFileRequest\x1a\x1c.nameserver.StatFileResponseB\n" +
	"Z\b./;protob\x06proto3"

var (
	file_nameserver_proto_rawDescOnce sync.Once
	file_nameserver_proto_rawDescData []byte
)

func file_nameserver_proto_rawDescGZIP() []byte {
	file_nameserver_proto_rawDescOnce.Do(func() {
		file_nameserver_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_nameserver_proto_rawDesc), len(file_nameserver_proto_rawDesc)))
	})
	return file_nameserver_proto_rawDescData
}

var file_nameserver_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_nameserver_proto_goTypes = []any{
	(*Permission)(nil),         // 0: nameserver.Permission
	(*Permissions)(nil),        // 1: nameserver.Permissions
	(*DirEntry)(nil),           // 2: nameserver.DirEntry
	(*StatBlockInfo)(nil),      // 3: nameserver.StatBlockInfo
	(*LoginRequest)(nil),       // 4: nameserver.LoginRequest
	(*LoginResponse)(nil),      // 5: nameserver.LoginResponse
	(*LogoutRequest)(nil),      // 6: nameserver.LogoutRequest
	(*LogoutResponse)(nil),     // 7: nameserver.LogoutResponse
	(*CreateFileRequest)(nil),  // 8: nameserver.CreateFileRequest
	(*CreateFileResponse)(nil), // 9: nameserver.CreateFileResponse
	(*CreateDirRequest)(nil),   // 10: nameserver.CreateDirRequest
	(*CreateDirResponse)(nil),  // 11: nameserver.CreateDirResponse
	(*DeleteFileRequest)(nil),  // 12: nameserver.DeleteFileRequest
	(*DeleteFileResponse)(nil), // 13: nameserver.DeleteFileResponse
	(*DeleteDirRequest)(nil),   // 14: nameserver.DeleteDirRequest
	(*DeleteDirResponse)(nil),  // 15: nameserver.DeleteDirResponse
	(*ListDirRequest)(nil),     // 16: nameserver.ListDirRequest
	(*ListDirResponse)(nil),    // 17: nameserver.ListDirResponse
	(*StatFileRequest)(nil),    // 18: nameserver.StatFileRequest
	(*StatFileResponse)(nil),   // 19: nameserver.StatFileResponse
}
var file_nameserver_proto_depIdxs = []int32{
	0,  // 0: nameserver.Permissions.ownerPermission:type_name -> nameserver.Permission
	0,  // 1: nameserver.Permissions.groupPermission:type_name -> nameserver.Permission
	0,  // 2: nameserver.Permissions.otherPermission:type_name -> nameserver.Permission
	1,  // 3: nameserver.DirEntry.permissions:type_name -> nameserver.Permissions
	1,  // 4: nameserver.CreateFileRequest.permissions:type_name -> nameserver.Permissions
	1,  // 5: nameserver.CreateDirRequest.permissions:type_name -> nameserver.Permissions
	2,  // 6: nameserver.ListDirResponse.entries:type_name -> nameserver.DirEntry
	2,  // 7: nameserver.StatFileResponse.entry:type_name -> nameserver.DirEntry
	3,  // 8: nameserver.StatFileResponse.blockInfos:type_name -> nameserver.StatBlockInfo
	4,  // 9: nameserver.Name.Login:input_type -> nameserver.LoginRequest
	6,  // 10: nameserver.Name.Logout:input_type -> nameserver.LogoutRequest
	8,  // 11: nameserver.Name.CreateFile:input_type -> nameserver.CreateFileRequest
	10, // 12: nameserver.Name.CreateDir:input_type -> nameserver.CreateDirRequest
	12, // 13: nameserver.Name.DeleteFile:input_type -> nameserver.DeleteFileRequest
	14, // 14: nameserver.Name.DeleteDir:input_type -> nameserver.DeleteDirRequest
	16, // 15: nameserver.Name.ListDir:input_type -> nameserver.ListDirRequest
	18, // 16: nameserver.Name.StatFile:input_type -> nameserver.StatFileRequest
	5,  // 17: nameserver.Name.Login:output_type -> nameserver.LoginResponse
	7,  // 18: nameserver.Name.Logout:output_type -> nameserver.LogoutResponse
	9,  // 19: nameserver.Name.CreateFile:output_type -> nameserver.CreateFileResponse
	11, // 20: nameserver.Name.CreateDir:output_type -> nameserver.CreateDirResponse
	13, // 21: nameserver.Name.DeleteFile:output_type -> nameserver.DeleteFileResponse
	15, // 22: nameserver.Name.DeleteDir:output_type -> nameserver.DeleteDirResponse
	17, // 23: nameserver.Name.ListDir:output_type -> nameserver.ListDirResponse
	19, // 24: nameserver.Name.StatFile:output_type -> nameserver.StatFileResponse
	17, // [17:25] is the sub-list for method output_type
	9,  // [9:17] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_nameserver_proto_init() }
func file_nameserver_proto_init() {
	if File_nameserver_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_nameserver_proto_rawDesc), len(file_nameserver_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_nameserver_proto_goTypes,
		DependencyIndexes: file_nameserver_proto_depIdxs,
		MessageInfos:      file_nameserver_proto_msgTypes,
	}.Build()
	File_nameserver_proto = out.File
	file_nameserver_proto_goTypes = nil
	file_nameserver_proto_depIdxs = nil
}
