// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: nodeserver.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BlockInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BlockId       uint64                 `protobuf:"varint,1,opt,name=blockId,proto3" json:"blockId,omitempty"`
	Crc           uint32                 `protobuf:"varint,2,opt,name=crc,proto3" json:"crc,omitempty"`
	Sequence      uint64                 `protobuf:"varint,3,opt,name=sequence,proto3" json:"sequence,omitempty"`
	Length        uint32                 `protobuf:"varint,4,opt,name=length,proto3" json:"length,omitempty"`
	Path          string                 `protobuf:"bytes,5,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlockInfo) Reset() {
	*x = BlockInfo{}
	mi := &file_nodeserver_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlockInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockInfo) ProtoMessage() {}

func (x *BlockInfo) ProtoReflect() protoreflect.Message {
	mi := &file_nodeserver_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockInfo.ProtoReflect.Descriptor instead.
func (*BlockInfo) Descriptor() ([]byte, []int) {
	return file_nodeserver_proto_rawDescGZIP(), []int{0}
}

func (x *BlockInfo) GetBlockId() uint64 {
	if x != nil {
		return x.BlockId
	}
	return 0
}

func (x *BlockInfo) GetCrc() uint32 {
	if x != nil {
		return x.Crc
	}
	return 0
}

func (x *BlockInfo) GetSequence() uint64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *BlockInfo) GetLength() uint32 {
	if x != nil {
		return x.Length
	}
	return 0
}

func (x *BlockInfo) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

// Define a User message
type GetBlockInfosRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBlockInfosRequest) Reset() {
	*x = GetBlockInfosRequest{}
	mi := &file_nodeserver_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBlockInfosRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBlockInfosRequest) ProtoMessage() {}

func (x *GetBlockInfosRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nodeserver_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBlockInfosRequest.ProtoReflect.Descriptor instead.
func (*GetBlockInfosRequest) Descriptor() ([]byte, []int) {
	return file_nodeserver_proto_rawDescGZIP(), []int{1}
}

type GetBlockInfosResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BlockInfos    []*BlockInfo           `protobuf:"bytes,1,rep,name=blockInfos,proto3" json:"blockInfos,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBlockInfosResponse) Reset() {
	*x = GetBlockInfosResponse{}
	mi := &file_nodeserver_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBlockInfosResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBlockInfosResponse) ProtoMessage() {}

func (x *GetBlockInfosResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nodeserver_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBlockInfosResponse.ProtoReflect.Descriptor instead.
func (*GetBlockInfosResponse) Descriptor() ([]byte, []int) {
	return file_nodeserver_proto_rawDescGZIP(), []int{2}
}

func (x *GetBlockInfosResponse) GetBlockInfos() []*BlockInfo {
	if x != nil {
		return x.BlockInfos
	}
	return nil
}

type GetBlockInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBlockInfoRequest) Reset() {
	*x = GetBlockInfoRequest{}
	mi := &file_nodeserver_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBlockInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBlockInfoRequest) ProtoMessage() {}

func (x *GetBlockInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nodeserver_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBlockInfoRequest.ProtoReflect.Descriptor instead.
func (*GetBlockInfoRequest) Descriptor() ([]byte, []int) {
	return file_nodeserver_proto_rawDescGZIP(), []int{3}
}

func (x *GetBlockInfoRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetBlockInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BlockInfo     *BlockInfo             `protobuf:"bytes,1,opt,name=blockInfo,proto3" json:"blockInfo,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBlockInfoResponse) Reset() {
	*x = GetBlockInfoResponse{}
	mi := &file_nodeserver_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBlockInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBlockInfoResponse) ProtoMessage() {}

func (x *GetBlockInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nodeserver_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBlockInfoResponse.ProtoReflect.Descriptor instead.
func (*GetBlockInfoResponse) Descriptor() ([]byte, []int) {
	return file_nodeserver_proto_rawDescGZIP(), []int{4}
}

func (x *GetBlockInfoResponse) GetBlockInfo() *BlockInfo {
	if x != nil {
		return x.BlockInfo
	}
	return nil
}

type GetBlockRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBlockRequest) Reset() {
	*x = GetBlockRequest{}
	mi := &file_nodeserver_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBlockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBlockRequest) ProtoMessage() {}

func (x *GetBlockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nodeserver_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBlockRequest.ProtoReflect.Descriptor instead.
func (*GetBlockRequest) Descriptor() ([]byte, []int) {
	return file_nodeserver_proto_rawDescGZIP(), []int{5}
}

func (x *GetBlockRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetBlockResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BlockInfo     *BlockInfo             `protobuf:"bytes,1,opt,name=blockInfo,proto3" json:"blockInfo,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBlockResponse) Reset() {
	*x = GetBlockResponse{}
	mi := &file_nodeserver_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBlockResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBlockResponse) ProtoMessage() {}

func (x *GetBlockResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nodeserver_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBlockResponse.ProtoReflect.Descriptor instead.
func (*GetBlockResponse) Descriptor() ([]byte, []int) {
	return file_nodeserver_proto_rawDescGZIP(), []int{6}
}

func (x *GetBlockResponse) GetBlockInfo() *BlockInfo {
	if x != nil {
		return x.BlockInfo
	}
	return nil
}

func (x *GetBlockResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type WriteBlockRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BlockInfo     *BlockInfo             `protobuf:"bytes,1,opt,name=blockInfo,proto3" json:"blockInfo,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteBlockRequest) Reset() {
	*x = WriteBlockRequest{}
	mi := &file_nodeserver_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteBlockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteBlockRequest) ProtoMessage() {}

func (x *WriteBlockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nodeserver_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteBlockRequest.ProtoReflect.Descriptor instead.
func (*WriteBlockRequest) Descriptor() ([]byte, []int) {
	return file_nodeserver_proto_rawDescGZIP(), []int{7}
}

func (x *WriteBlockRequest) GetBlockInfo() *BlockInfo {
	if x != nil {
		return x.BlockInfo
	}
	return nil
}

func (x *WriteBlockRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type WriteBlockResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BlockInfo     *BlockInfo             `protobuf:"bytes,1,opt,name=blockInfo,proto3" json:"blockInfo,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteBlockResponse) Reset() {
	*x = WriteBlockResponse{}
	mi := &file_nodeserver_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteBlockResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteBlockResponse) ProtoMessage() {}

func (x *WriteBlockResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nodeserver_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteBlockResponse.ProtoReflect.Descriptor instead.
func (*WriteBlockResponse) Descriptor() ([]byte, []int) {
	return file_nodeserver_proto_rawDescGZIP(), []int{8}
}

func (x *WriteBlockResponse) GetBlockInfo() *BlockInfo {
	if x != nil {
		return x.BlockInfo
	}
	return nil
}

type DeleteBlockRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteBlockRequest) Reset() {
	*x = DeleteBlockRequest{}
	mi := &file_nodeserver_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteBlockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteBlockRequest) ProtoMessage() {}

func (x *DeleteBlockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nodeserver_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteBlockRequest.ProtoReflect.Descriptor instead.
func (*DeleteBlockRequest) Descriptor() ([]byte, []int) {
	return file_nodeserver_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteBlockRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeleteBlockResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteBlockResponse) Reset() {
	*x = DeleteBlockResponse{}
	mi := &file_nodeserver_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteBlockResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteBlockResponse) ProtoMessage() {}

func (x *DeleteBlockResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nodeserver_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteBlockResponse.ProtoReflect.Descriptor instead.
func (*DeleteBlockResponse) Descriptor() ([]byte, []int) {
	return file_nodeserver_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteBlockResponse) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type CopyBlockRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	DestinationUrl string                 `protobuf:"bytes,2,opt,name=destinationUrl,proto3" json:"destinationUrl,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CopyBlockRequest) Reset() {
	*x = CopyBlockRequest{}
	mi := &file_nodeserver_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CopyBlockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CopyBlockRequest) ProtoMessage() {}

func (x *CopyBlockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nodeserver_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CopyBlockRequest.ProtoReflect.Descriptor instead.
func (*CopyBlockRequest) Descriptor() ([]byte, []int) {
	return file_nodeserver_proto_rawDescGZIP(), []int{11}
}

func (x *CopyBlockRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CopyBlockRequest) GetDestinationUrl() string {
	if x != nil {
		return x.DestinationUrl
	}
	return ""
}

type CopyBlockResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CopyBlockResponse) Reset() {
	*x = CopyBlockResponse{}
	mi := &file_nodeserver_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CopyBlockResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CopyBlockResponse) ProtoMessage() {}

func (x *CopyBlockResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nodeserver_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CopyBlockResponse.ProtoReflect.Descriptor instead.
func (*CopyBlockResponse) Descriptor() ([]byte, []int) {
	return file_nodeserver_proto_rawDescGZIP(), []int{12}
}

var File_nodeserver_proto protoreflect.FileDescriptor

const file_nodeserver_proto_rawDesc = "" +
	"\n" +
	"\x10nodeserver.proto\x12\n" +
	"nodeserver\"\x7f\n" +
	"\tBlockInfo\x12\x18\n" +
	"\ablockId\x18\x01 \x01(\x04R\ablockId\x12\x10\n" +
	"\x03crc\x18\x02 \x01(\rR\x03crc\x12\x1a\n" +
	"\bsequence\x18\x03 \x01(\x04R\bsequence\x12\x16\n" +
	"\x06length\x18\x04 \x01(\rR\x06length\x12\x12\n" +
	"\x04path\x18\x05 \x01(\tR\x04path\"\x16\n" +
	"\x14GetBlockInfosRequest\"N\n" +
	"\x15GetBlockInfosResponse\x125\n" +
	"\n" +
	"blockInfos\x18\x01 \x03(\v2\x15.nodeserver.BlockInfoR\n" +
	"blockInfos\"%\n" +
	"\x13GetBlockInfoRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\"K\n" +
	"\x14GetBlockInfoResponse\x123\n" +
	"\tblockInfo\x18\x01 \x01(\v2\x15.nodeserver.BlockInfoR\tblockInfo\"!\n" +
	"\x0fGetBlockRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\"[\n" +
	"\x10GetBlockResponse\x123\n" +
	"\tblockInfo\x18\x01 \x01(\v2\x15.nodeserver.BlockInfoR\tblockInfo\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\"\\\n" +
	"\x11WriteBlockRequest\x123\n" +
	"\tblockInfo\x18\x01 \x01(\v2\x15.nodeserver.BlockInfoR\tblockInfo\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\"I\n" +
	"\x12WriteBlockResponse\x123\n" +
	"\tblockInfo\x18\x01 \x01(\v2\x15.nodeserver.BlockInfoR\tblockInfo\"$\n" +
	"\x12DeleteBlockRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\"%\n" +
	"\x13DeleteBlockResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\"J\n" +
	"\x10CopyBlockRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12&\n" +
	"\x0edestinationUrl\x18\x02 \x01(\tR\x0edestinationUrl\"\x13\n" +
	"\x11CopyBlockResponse2\xdd\x03\n" +
	"\x04Node\x12T\n" +
	"\rGetBlockInfos\x12 .nodeserver.GetBlockInfosRequest\x1a!.nodeserver.GetBlockInfosResponse\x12Q\n" +
	"\fGetBlockInfo\x12\x1f.nodeserver.GetBlockInfoRequest\x1a .nodeserver.GetBlockInfoResponse\x12E\n" +
	"\bGetBlock\x12\x1b.nodeserver.GetBlockRequest\x1a\x1c.nodeserver.GetBlockResponse\x12K\n" +
	"\n" +
	"WriteBlock\x12\x1d.nodeserver.WriteBlockRequest\x1a\x1e.nodeserver.WriteBlockResponse\x12N\n" +
	"\vDeleteBlock\x12\x1e.nodeserver.DeleteBlockRequest\x1a\x1f.nodeserver.DeleteBlockResponse\x12H\n" +
	"\tCopyBlock\x12\x1c.nodeserver.CopyBlockRequest\x1a\x1d.nodeserver.CopyBlockResponseB\n" +
	"Z\b./;protob\x06proto3"

var (
	file_nodeserver_proto_rawDescOnce sync.Once
	file_nodeserver_proto_rawDescData []byte
)

func file_nodeserver_proto_rawDescGZIP() []byte {
	file_nodeserver_proto_rawDescOnce.Do(func() {
		file_nodeserver_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_nodeserver_proto_rawDesc), len(file_nodeserver_proto_rawDesc)))
	})
	return file_nodeserver_proto_rawDescData
}

var file_nodeserver_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_nodeserver_proto_goTypes = []any{
	(*BlockInfo)(nil),             // 0: nodeserver.BlockInfo
	(*GetBlockInfosRequest)(nil),  // 1: nodeserver.GetBlockInfosRequest
	(*GetBlockInfosResponse)(nil), // 2: nodeserver.GetBlockInfosResponse
	(*GetBlockInfoRequest)(nil),   // 3: nodeserver.GetBlockInfoRequest
	(*GetBlockInfoResponse)(nil),  // 4: nodeserver.GetBlockInfoResponse
	(*GetBlockRequest)(nil),       // 5: nodeserver.GetBlockRequest
	(*GetBlockResponse)(nil),      // 6: nodeserver.GetBlockResponse
	(*WriteBlockRequest)(nil),     // 7: nodeserver.WriteBlockRequest
	(*WriteBlockResponse)(nil),    // 8: nodeserver.WriteBlockResponse
	(*DeleteBlockRequest)(nil),    // 9: nodeserver.DeleteBlockRequest
	(*DeleteBlockResponse)(nil),   // 10: nodeserver.DeleteBlockResponse
	(*CopyBlockRequest)(nil),      // 11: nodeserver.CopyBlockRequest
	(*CopyBlockResponse)(nil),     // 12: nodeserver.CopyBlockResponse
}
var file_nodeserver_proto_depIdxs = []int32{
	0,  // 0: nodeserver.GetBlockInfosResponse.blockInfos:type_name -> nodeserver.BlockInfo
	0,  // 1: nodeserver.GetBlockInfoResponse.blockInfo:type_name -> nodeserver.BlockInfo
	0,  // 2: nodeserver.GetBlockResponse.blockInfo:type_name -> nodeserver.BlockInfo
	0,  // 3: nodeserver.WriteBlockRequest.blockInfo:type_name -> nodeserver.BlockInfo
	0,  // 4: nodeserver.WriteBlockResponse.blockInfo:type_name -> nodeserver.BlockInfo
	1,  // 5: nodeserver.Node.GetBlockInfos:input_type -> nodeserver.GetBlockInfosRequest
	3,  // 6: nodeserver.Node.GetBlockInfo:input_type -> nodeserver.GetBlockInfoRequest
	5,  // 7: nodeserver.Node.GetBlock:input_type -> nodeserver.GetBlockRequest
	7,  // 8: nodeserver.Node.WriteBlock:input_type -> nodeserver.WriteBlockRequest
	9,  // 9: nodeserver.Node.DeleteBlock:input_type -> nodeserver.DeleteBlockRequest
	11, // 10: nodeserver.Node.CopyBlock:input_type -> nodeserver.CopyBlockRequest
	2,  // 11: nodeserver.Node.GetBlockInfos:output_type -> nodeserver.GetBlockInfosResponse
	4,  // 12: nodeserver.Node.GetBlockInfo:output_type -> nodeserver.GetBlockInfoResponse
	6,  // 13: nodeserver.Node.GetBlock:output_type -> nodeserver.GetBlockResponse
	8,  // 14: nodeserver.Node.WriteBlock:output_type -> nodeserver.WriteBlockResponse
	10, // 15: nodeserver.Node.DeleteBlock:output_type -> nodeserver.DeleteBlockResponse
	12, // 16: nodeserver.Node.CopyBlock:output_type -> nodeserver.CopyBlockResponse
	11, // [11:17] is the sub-list for method output_type
	5,  // [5:11] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_nodeserver_proto_init() }
func file_nodeserver_proto_init() {
	if File_nodeserver_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_nodeserver_proto_rawDesc), len(file_nodeserver_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_nodeserver_proto_goTypes,
		DependencyIndexes: file_nodeserver_proto_depIdxs,
		MessageInfos:      file_nodeserver_proto_msgTypes,
	}.Build()
	File_nodeserver_proto = out.File
	file_nodeserver_proto_goTypes = nil
	file_nodeserver_proto_depIdxs = nil
}
