// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: notifications.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NotifyBlockPresentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Host          string                 `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`
	BlockId       string                 `protobuf:"bytes,2,opt,name=blockId,proto3" json:"blockId,omitempty"`
	Path          string                 `protobuf:"bytes,3,opt,name=path,proto3" json:"path,omitempty"`
	Crc           uint32                 `protobuf:"varint,4,opt,name=crc,proto3" json:"crc,omitempty"`
	Sequence      uint64                 `protobuf:"varint,5,opt,name=sequence,proto3" json:"sequence,omitempty"`
	Length        uint32                 `protobuf:"varint,6,opt,name=length,proto3" json:"length,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotifyBlockPresentRequest) Reset() {
	*x = NotifyBlockPresentRequest{}
	mi := &file_notifications_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotifyBlockPresentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotifyBlockPresentRequest) ProtoMessage() {}

func (x *NotifyBlockPresentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_notifications_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotifyBlockPresentRequest.ProtoReflect.Descriptor instead.
func (*NotifyBlockPresentRequest) Descriptor() ([]byte, []int) {
	return file_notifications_proto_rawDescGZIP(), []int{0}
}

func (x *NotifyBlockPresentRequest) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *NotifyBlockPresentRequest) GetBlockId() string {
	if x != nil {
		return x.BlockId
	}
	return ""
}

func (x *NotifyBlockPresentRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *NotifyBlockPresentRequest) GetCrc() uint32 {
	if x != nil {
		return x.Crc
	}
	return 0
}

func (x *NotifyBlockPresentRequest) GetSequence() uint64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *NotifyBlockPresentRequest) GetLength() uint32 {
	if x != nil {
		return x.Length
	}
	return 0
}

type NotifyBlockPresentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotifyBlockPresentResponse) Reset() {
	*x = NotifyBlockPresentResponse{}
	mi := &file_notifications_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotifyBlockPresentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotifyBlockPresentResponse) ProtoMessage() {}

func (x *NotifyBlockPresentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_notifications_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotifyBlockPresentResponse.ProtoReflect.Descriptor instead.
func (*NotifyBlockPresentResponse) Descriptor() ([]byte, []int) {
	return file_notifications_proto_rawDescGZIP(), []int{1}
}

type NotifyBlockAddedRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Host          string                 `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`
	BlockId       string                 `protobuf:"bytes,2,opt,name=blockId,proto3" json:"blockId,omitempty"`
	Path          string                 `protobuf:"bytes,3,opt,name=path,proto3" json:"path,omitempty"`
	Crc           uint32                 `protobuf:"varint,4,opt,name=crc,proto3" json:"crc,omitempty"`
	Sequence      uint64                 `protobuf:"varint,5,opt,name=sequence,proto3" json:"sequence,omitempty"`
	Length        uint32                 `protobuf:"varint,6,opt,name=length,proto3" json:"length,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotifyBlockAddedRequest) Reset() {
	*x = NotifyBlockAddedRequest{}
	mi := &file_notifications_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotifyBlockAddedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotifyBlockAddedRequest) ProtoMessage() {}

func (x *NotifyBlockAddedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_notifications_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotifyBlockAddedRequest.ProtoReflect.Descriptor instead.
func (*NotifyBlockAddedRequest) Descriptor() ([]byte, []int) {
	return file_notifications_proto_rawDescGZIP(), []int{2}
}

func (x *NotifyBlockAddedRequest) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *NotifyBlockAddedRequest) GetBlockId() string {
	if x != nil {
		return x.BlockId
	}
	return ""
}

func (x *NotifyBlockAddedRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *NotifyBlockAddedRequest) GetCrc() uint32 {
	if x != nil {
		return x.Crc
	}
	return 0
}

func (x *NotifyBlockAddedRequest) GetSequence() uint64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *NotifyBlockAddedRequest) GetLength() uint32 {
	if x != nil {
		return x.Length
	}
	return 0
}

type NotifyBlockAddedResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotifyBlockAddedResponse) Reset() {
	*x = NotifyBlockAddedResponse{}
	mi := &file_notifications_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotifyBlockAddedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotifyBlockAddedResponse) ProtoMessage() {}

func (x *NotifyBlockAddedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_notifications_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotifyBlockAddedResponse.ProtoReflect.Descriptor instead.
func (*NotifyBlockAddedResponse) Descriptor() ([]byte, []int) {
	return file_notifications_proto_rawDescGZIP(), []int{3}
}

type NotifyBlockRemovedRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Host          string                 `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`
	BlockId       string                 `protobuf:"bytes,2,opt,name=blockId,proto3" json:"blockId,omitempty"`
	Path          string                 `protobuf:"bytes,3,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotifyBlockRemovedRequest) Reset() {
	*x = NotifyBlockRemovedRequest{}
	mi := &file_notifications_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotifyBlockRemovedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotifyBlockRemovedRequest) ProtoMessage() {}

func (x *NotifyBlockRemovedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_notifications_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotifyBlockRemovedRequest.ProtoReflect.Descriptor instead.
func (*NotifyBlockRemovedRequest) Descriptor() ([]byte, []int) {
	return file_notifications_proto_rawDescGZIP(), []int{4}
}

func (x *NotifyBlockRemovedRequest) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *NotifyBlockRemovedRequest) GetBlockId() string {
	if x != nil {
		return x.BlockId
	}
	return ""
}

func (x *NotifyBlockRemovedRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type NotifyBlockRemovedResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotifyBlockRemovedResponse) Reset() {
	*x = NotifyBlockRemovedResponse{}
	mi := &file_notifications_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotifyBlockRemovedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotifyBlockRemovedResponse) ProtoMessage() {}

func (x *NotifyBlockRemovedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_notifications_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotifyBlockRemovedResponse.ProtoReflect.Descriptor instead.
func (*NotifyBlockRemovedResponse) Descriptor() ([]byte, []int) {
	return file_notifications_proto_rawDescGZIP(), []int{5}
}

var File_notifications_proto protoreflect.FileDescriptor

const file_notifications_proto_rawDesc = "" +
	"\n" +
	"\x13notifications.proto\x12\fnotification\"\xa3\x01\n" +
	"\x19NotifyBlockPresentRequest\x12\x12\n" +
	"\x04host\x18\x01 \x01(\tR\x04host\x12\x18\n" +
	"\ablockId\x18\x02 \x01(\tR\ablockId\x12\x12\n" +
	"\x04path\x18\x03 \x01(\tR\x04path\x12\x10\n" +
	"\x03crc\x18\x04 \x01(\rR\x03crc\x12\x1a\n" +
	"\bsequence\x18\x05 \x01(\x04R\bsequence\x12\x16\n" +
	"\x06length\x18\x06 \x01(\rR\x06length\"\x1c\n" +
	"\x1aNotifyBlockPresentResponse\"\xa1\x01\n" +
	"\x17NotifyBlockAddedRequest\x12\x12\n" +
	"\x04host\x18\x01 \x01(\tR\x04host\x12\x18\n" +
	"\ablockId\x18\x02 \x01(\tR\ablockId\x12\x12\n" +
	"\x04path\x18\x03 \x01(\tR\x04path\x12\x10\n" +
	"\x03crc\x18\x04 \x01(\rR\x03crc\x12\x1a\n" +
	"\bsequence\x18\x05 \x01(\x04R\bsequence\x12\x16\n" +
	"\x06length\x18\x06 \x01(\rR\x06length\"\x1a\n" +
	"\x18NotifyBlockAddedResponse\"]\n" +
	"\x19NotifyBlockRemovedRequest\x12\x12\n" +
	"\x04host\x18\x01 \x01(\tR\x04host\x12\x18\n" +
	"\ablockId\x18\x02 \x01(\tR\ablockId\x12\x12\n" +
	"\x04path\x18\x03 \x01(\tR\x04path\"\x1c\n" +
	"\x1aNotifyBlockRemovedResponse2\xc2\x02\n" +
	"\fNotification\x12g\n" +
	"\x12NotifyBlockPresent\x12'.notification.NotifyBlockPresentRequest\x1a(.notification.NotifyBlockPresentResponse\x12`\n" +
	"\x10NotifyBlockAdded\x12%.notification.NotifyBlockAddedRequest\x1a%.notification.NotifyBlockAddedRequest\x12g\n" +
	"\x12NotifyBlockRemoved\x12'.notification.NotifyBlockRemovedRequest\x1a(.notification.NotifyBlockRemovedResponseB\n" +
	"Z\b./;protob\x06proto3"

var (
	file_notifications_proto_rawDescOnce sync.Once
	file_notifications_proto_rawDescData []byte
)

func file_notifications_proto_rawDescGZIP() []byte {
	file_notifications_proto_rawDescOnce.Do(func() {
		file_notifications_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_notifications_proto_rawDesc), len(file_notifications_proto_rawDesc)))
	})
	return file_notifications_proto_rawDescData
}

var file_notifications_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_notifications_proto_goTypes = []any{
	(*NotifyBlockPresentRequest)(nil),  // 0: notification.NotifyBlockPresentRequest
	(*NotifyBlockPresentResponse)(nil), // 1: notification.NotifyBlockPresentResponse
	(*NotifyBlockAddedRequest)(nil),    // 2: notification.NotifyBlockAddedRequest
	(*NotifyBlockAddedResponse)(nil),   // 3: notification.NotifyBlockAddedResponse
	(*NotifyBlockRemovedRequest)(nil),  // 4: notification.NotifyBlockRemovedRequest
	(*NotifyBlockRemovedResponse)(nil), // 5: notification.NotifyBlockRemovedResponse
}
var file_notifications_proto_depIdxs = []int32{
	0, // 0: notification.Notification.NotifyBlockPresent:input_type -> notification.NotifyBlockPresentRequest
	2, // 1: notification.Notification.NotifyBlockAdded:input_type -> notification.NotifyBlockAddedRequest
	4, // 2: notification.Notification.NotifyBlockRemoved:input_type -> notification.NotifyBlockRemovedRequest
	1, // 3: notification.Notification.NotifyBlockPresent:output_type -> notification.NotifyBlockPresentResponse
	2, // 4: notification.Notification.NotifyBlockAdded:output_type -> notification.NotifyBlockAddedRequest
	5, // 5: notification.Notification.NotifyBlockRemoved:output_type -> notification.NotifyBlockRemovedResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_notifications_proto_init() }
func file_notifications_proto_init() {
	if File_notifications_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_notifications_proto_rawDesc), len(file_notifications_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_notifications_proto_goTypes,
		DependencyIndexes: file_notifications_proto_depIdxs,
		MessageInfos:      file_notifications_proto_msgTypes,
	}.Build()
	File_notifications_proto = out.File
	file_notifications_proto_goTypes = nil
	file_notifications_proto_depIdxs = nil
}
