// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: notifications.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Notification_NotifyBlockPresent_FullMethodName = "/notification.Notification/NotifyBlockPresent"
	Notification_NotifyBlockAdded_FullMethodName   = "/notification.Notification/NotifyBlockAdded"
	Notification_NotifyBlockRemoved_FullMethodName = "/notification.Notification/NotifyBlockRemoved"
)

// NotificationClient is the client API for Notification service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type NotificationClient interface {
	NotifyBlockPresent(ctx context.Context, in *NotifyBlockPresentRequest, opts ...grpc.CallOption) (*NotifyBlockPresentResponse, error)
	NotifyBlockAdded(ctx context.Context, in *NotifyBlockAddedRequest, opts ...grpc.CallOption) (*NotifyBlockAddedRequest, error)
	NotifyBlockRemoved(ctx context.Context, in *NotifyBlockRemovedRequest, opts ...grpc.CallOption) (*NotifyBlockRemovedResponse, error)
}

type notificationClient struct {
	cc grpc.ClientConnInterface
}

func NewNotificationClient(cc grpc.ClientConnInterface) NotificationClient {
	return &notificationClient{cc}
}

func (c *notificationClient) NotifyBlockPresent(ctx context.Context, in *NotifyBlockPresentRequest, opts ...grpc.CallOption) (*NotifyBlockPresentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NotifyBlockPresentResponse)
	err := c.cc.Invoke(ctx, Notification_NotifyBlockPresent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notificationClient) NotifyBlockAdded(ctx context.Context, in *NotifyBlockAddedRequest, opts ...grpc.CallOption) (*NotifyBlockAddedRequest, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NotifyBlockAddedRequest)
	err := c.cc.Invoke(ctx, Notification_NotifyBlockAdded_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notificationClient) NotifyBlockRemoved(ctx context.Context, in *NotifyBlockRemovedRequest, opts ...grpc.CallOption) (*NotifyBlockRemovedResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NotifyBlockRemovedResponse)
	err := c.cc.Invoke(ctx, Notification_NotifyBlockRemoved_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NotificationServer is the server API for Notification service.
// All implementations must embed UnimplementedNotificationServer
// for forward compatibility.
type NotificationServer interface {
	NotifyBlockPresent(context.Context, *NotifyBlockPresentRequest) (*NotifyBlockPresentResponse, error)
	NotifyBlockAdded(context.Context, *NotifyBlockAddedRequest) (*NotifyBlockAddedRequest, error)
	NotifyBlockRemoved(context.Context, *NotifyBlockRemovedRequest) (*NotifyBlockRemovedResponse, error)
	mustEmbedUnimplementedNotificationServer()
}

// UnimplementedNotificationServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedNotificationServer struct{}

func (UnimplementedNotificationServer) NotifyBlockPresent(context.Context, *NotifyBlockPresentRequest) (*NotifyBlockPresentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NotifyBlockPresent not implemented")
}
func (UnimplementedNotificationServer) NotifyBlockAdded(context.Context, *NotifyBlockAddedRequest) (*NotifyBlockAddedRequest, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NotifyBlockAdded not implemented")
}
func (UnimplementedNotificationServer) NotifyBlockRemoved(context.Context, *NotifyBlockRemovedRequest) (*NotifyBlockRemovedResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NotifyBlockRemoved not implemented")
}
func (UnimplementedNotificationServer) mustEmbedUnimplementedNotificationServer() {}
func (UnimplementedNotificationServer) testEmbeddedByValue()                      {}

// UnsafeNotificationServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NotificationServer will
// result in compilation errors.
type UnsafeNotificationServer interface {
	mustEmbedUnimplementedNotificationServer()
}

func RegisterNotificationServer(s grpc.ServiceRegistrar, srv NotificationServer) {
	// If the following call pancis, it indicates UnimplementedNotificationServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Notification_ServiceDesc, srv)
}

func _Notification_NotifyBlockPresent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NotifyBlockPresentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotificationServer).NotifyBlockPresent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Notification_NotifyBlockPresent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotificationServer).NotifyBlockPresent(ctx, req.(*NotifyBlockPresentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Notification_NotifyBlockAdded_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NotifyBlockAddedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotificationServer).NotifyBlockAdded(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Notification_NotifyBlockAdded_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotificationServer).NotifyBlockAdded(ctx, req.(*NotifyBlockAddedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Notification_NotifyBlockRemoved_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NotifyBlockRemovedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotificationServer).NotifyBlockRemoved(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Notification_NotifyBlockRemoved_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotificationServer).NotifyBlockRemoved(ctx, req.(*NotifyBlockRemovedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Notification_ServiceDesc is the grpc.ServiceDesc for Notification service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Notification_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "notification.Notification",
	HandlerType: (*NotificationServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "NotifyBlockPresent",
			Handler:    _Notification_NotifyBlockPresent_Handler,
		},
		{
			MethodName: "NotifyBlockAdded",
			Handler:    _Notification_NotifyBlockAdded_Handler,
		},
		{
			MethodName: "NotifyBlockRemoved",
			Handler:    _Notification_NotifyBlockRemoved_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "notifications.proto",
}
